{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.deployment_wlm_scheduler }}
{{- $envAll := . }}

{{- $mounts_triliovault_wlm_scheduler := .Values.pod.mounts.triliovault_wlm_scheduler.triliovault_wlm_scheduler }}
{{- $mounts_triliovault_wlm_scheduler_init := .Values.pod.mounts.triliovault_wlm_scheduler.init_container }}

{{- $tlsSecret := "" -}}
{{- if .Values.manifests.certificates -}}
{{- $tlsSecret := .Values.secrets.tls.workloads.wlm_api.internal -}}
{{- end -}}



{{- $serviceAccountName := "triliovault-wlm-scheduler" }}
{{ tuple $envAll "wlm_scheduler" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliovault-wlm-scheduler
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "triliovault" "wlm-scheduler" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.pod.replicas.triliovault_wlm_scheduler }}
  selector:
    matchLabels:
{{ tuple $envAll "triliovault" "wlm-scheduler" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "triliovault" "wlm-scheduler" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        runAsUser: 42424
        fsGroup: 42424
      affinity:
{{ tuple $envAll "triliovault" "wlm-scheduler" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.wlm_scheduler.node_selector_key }}: {{ .Values.labels.wlm_scheduler.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.pod.lifecycle.termination_grace_period.wlm_scheduler.timeout | default "30" }}
{{ if .Values.conf.triliovault.docker_registry_auth_enabled }}
      imagePullSecrets:
        - name: triliovault-image-registry
{{ end }}
      initContainers:
{{ tuple $envAll "wlm_scheduler" $mounts_triliovault_wlm_scheduler_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: triliovault-wlm-scheduler-init
{{ tuple $envAll "triliovault_wlm_scheduler" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "triliovault" "container" "triliovault_wlm_init" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          env:
{{- with $env := dict "ksUserSecret" .Values.secrets.identity.admin "useCA" (ne $tlsSecret "") }}
{{- include "helm-toolkit.snippets.keystone_openrc_env_vars" $env | indent 12 }}
{{- end }}
            - name: POD_NAME
              value: "triliovault-wlm-scheduler"
          command:
            - /tmp/triliovault-wlm-scheduler-init.sh
          terminationMessagePath: /var/log/termination-log
          volumeMounts:
            - name: varlogtriliovault
              mountPath: /var/log/triliovault
            - name: triliovault-wlm-bin
              mountPath: /tmp/triliovault-wlm-scheduler-init.sh
              subPath: triliovault-wlm-init.sh
              readOnly: true
            - name: pod-shared-triliovault-wlm-scheduler
              mountPath: /tmp/pod-shared-triliovault-wlm-scheduler
      containers:
        - name: triliovault-wlm-scheduler
{{ tuple $envAll "triliovault_wlm_scheduler" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.wlm_scheduler | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "triliovault" "container" "triliovault_wlm_scheduler" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/triliovault-wlm-scheduler.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/triliovault-wlm-scheduler.sh
                  - stop
          volumeMounts:
            - name: pod-shared-triliovault-wlm-scheduler
              mountPath: /etc/workloadmgr/workloadmgr.conf
              subPath: triliovault-wlm-ids.conf
              readOnly: true
            - name: pod-tmp
              mountPath: /tmp
            - name: varlogtriliovault
              mountPath: /var/log/triliovault
            - name: triliovault-wlm-etc
              mountPath: /etc/triliovault-wlm/triliovault-wlm.conf
              subPath: triliovault-wlm.conf
              readOnly: true
            {{- if eq .Values.conf.triliovault.backup_target_type "s3" }}
            - mountPath: /etc/triliovault-object-store/triliovault-object-store.conf
              name: triliovault-wlm-etc
              readOnly: true
              subPath: triliovault-object-store-wlm-scheduler.conf
            - mountPath: /etc/fuse.conf
              name: triliovault-wlm-etc
              readOnly: true
              subPath: fuse.conf
            - mountPath: /etc/triliovault-wlm/s3-cert.pem
              name: triliovault-wlm-etc
              readOnly: true
              subPath: s3-cert.pem
            {{- end }}
            {{- if .Values.conf.wlm.DEFAULT.log_config_append }}
            - name: triliovault-wlm-etc
              mountPath: {{ .Values.conf.wlm.DEFAULT.log_config_append }}
              subPath: {{ base .Values.conf.wlm.DEFAULT.log_config_append }}
              readOnly: true
            {{- end }}
            - name: triliovault-wlm-etc
              mountPath: /etc/triliovault-wlm/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: triliovault-wlm-bin
              mountPath: /tmp/triliovault-wlm-scheduler.sh
              subPath: triliovault-wlm-scheduler.sh
              readOnly: true
            - name: pod-shared-triliovault-wlm-scheduler
              mountPath: /tmp/pod-shared-triliovault-wlm-scheduler
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_db_triliovault_wlm.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.secrets.tls.workloads.wlm_api.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_messaging.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{ if $mounts_triliovault_wlm_scheduler.volumeMounts }}{{ toYaml $mounts_triliovault_wlm_scheduler.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: varlogtriliovault
          hostPath:
            path: /var/log/triliovault
        - name: triliovault-wlm-etc
          secret:
            secretName: triliovault-etc
            defaultMode: 0444
        - name: triliovault-wlm-bin
          configMap:
            name: triliovault-bin
            defaultMode: 0555
        - name: pod-shared-triliovault-wlm-scheduler
          emptyDir: {}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_db_triliovault_datamover.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.secrets.tls.datamover.datamover_api.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_messaging.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{ if $mounts_triliovault_wlm_scheduler.volumes }}{{ toYaml $mounts_triliovault_wlm_scheduler.volumes | indent 8 }}{{ end }}
{{- end }}
